version: '3.8'

services:
  enablensw-ndis-crosswalk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enablensw-ndis-crosswalk
    ports:
      - "8502:8502"
    volumes:
      # Mount local directory for persistent uploads (optional)
      - ./uploads:/app/uploads
      # Mount for logs (optional)
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=200
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: enablensw-network